#!/usr/bin/env python3

DENO_CONF_FLAGS = [
    '--import-map', './src/import_map.json',
    '--lock', './src/lock.json'
]
DENO_EXEC_FLAGS = ['-A']
DENO_COMP_FLAGS = ['--unstable', '--cached-only']


def cli():

    @command
    def install():
        cmd('deno', 'cache',
            *DENO_CONF_FLAGS, '--reload', './src/main.ts')

    @command
    def lock():
        cmd('deno', 'cache',
            *DENO_CONF_FLAGS, '--lock-write', './src/main.ts')

    @command
    def run():
        cmd('deno', 'run',
            *DENO_EXEC_FLAGS, *DENO_COMP_FLAGS,
            *DENO_CONF_FLAGS,
            './src/main.ts')

    @command
    def build():
        os.makedirs('dist', exist_ok=True)
        cmd('deno', 'compile',
            *DENO_EXEC_FLAGS, *DENO_COMP_FLAGS,
            *DENO_CONF_FLAGS,
            '--output', 'dist/pm',
            './src/main.ts')





# fmt: off
# https://gist.github.com/sirikon/d4327b6cc3de5cc244dbe5529d8f53ae
import inspect, sys, os, subprocess; os.chdir(os.path.dirname(__file__));commands = []
def cmd(*args, **kwargs): subprocess.run(args, **kwargs, check=True)
def spec(f): return inspect.getfullargspec(f)
def command(func): commands.append(func); return func
cli(); args = sys.argv[1:]
if len(args) == 0: print("Available commands:"); [print(' '.join([
    f' {f.__name__}',
    *[f'<{a}>' for a in spec(f).args],
    *([f'<...{spec(f).varargs}>'] if spec(f).varargs is not None else [])
])) for f in commands]; exit(0)
matching_commands = [f for f in commands if f.__name__ == args[0]]
if len(matching_commands) == 0: print(f'Unknown command "{args[0]}"');sys.exit(1)
try: matching_commands[0](*args[1:])
except KeyboardInterrupt: pass
except subprocess.CalledProcessError as err: sys.exit(err.returncode)
